import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { email } = await request.json();

    if (!email || !email.includes("@")) {
      return NextResponse.json(
        { error: "Invalid email address" },
        { status: 400 }
      );
    }

    // Here we'll use a simple approach to forward the email
    // In production, you would integrate with a service like SendGrid, Mailgun, or Resend

    // For now, we'll use the Resend API (a popular email service for Next.js)
    // You'll need to install the resend package and set up an API key

    // Send notification email to admin
    const adminResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ENTER_API_KEY_HERE`, // Replace with your Resend API key
      },
      body: JSON.stringify({
        from: "onboarding@resend.dev", // Using Resend's test domain
        to: "tryglimpse@yahoo.com",
        subject: "🎬 New Glimpse Early Access Request",
        html: `
          <!DOCTYPE html>
          <html>
            <head>
              <style>
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; }
                .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center; }
                .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
                .info-box { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #667eea; }
                .label { font-weight: bold; color: #667eea; margin-bottom: 5px; }
                .value { font-size: 16px; color: #333; }
                .footer { text-align: center; margin-top: 30px; color: #999; font-size: 14px; }
                .divider { height: 1px; background: #e0e0e0; margin: 20px 0; }
              </style>
            </head>
            <body>
              <div class="container">
                <div class="header">
                  <h1 style="margin: 0; font-size: 28px;">🎬 New Early Access Request</h1>
                  <p style="margin: 10px 0 0 0; opacity: 0.9;">Someone wants to join Glimpse!</p>
                </div>

                <div class="content">
                  <p style="font-size: 16px; margin-bottom: 20px;">
                    Great news! A new user has requested early access to Glimpse. They're excited to transform their product into cinematic 12-second stories.
                  </p>

                  <div class="info-box">
                    <div class="label">📧 Email Address</div>
                    <div class="value">${email}</div>
                  </div>

                  <div class="info-box">
                    <div class="label">🕐 Request Date & Time</div>
                    <div class="value">${new Date().toLocaleString('en-US', {
                      weekday: 'long',
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric',
                      hour: '2-digit',
                      minute: '2-digit',
                      timeZoneName: 'short'
                    })}</div>
                  </div>
                </div>

                <div class="footer">
                  <p>This email was automatically generated by Glimpse's early access system.</p>
                  <p style="margin-top: 10px;">© ${new Date().getFullYear()} Glimpse. All rights reserved.</p>
                </div>
              </div>
            </body>
          </html>
        `,
      }),
    });

    if (!adminResponse.ok) {
      console.error("Failed to send admin notification:", await adminResponse.json());
      return NextResponse.json(
        { error: "Failed to send notification" },
        { status: 500 }
      );
    }

    // Log the submission
    console.log("Email submission successful:", email);

    return NextResponse.json(
      { message: "Email submitted successfully" },
      { status: 200 }
    );
  } catch (error) {
    console.error("Error processing email submission:", error);
    return NextResponse.json(
      { error: "Failed to process submission" },
      { status: 500 }
    );
  }
}
